In [1]:
#-*- coding:utf-8 -*-
import tensorflow as tf
import numpy as np
import pandas as pd
import os 
from PIL import Image

C:\Users\all4git\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
def read_and_decode(filename):
    #根据文件名生成一个队列
    filename_queue = tf.train.string_input_producer([filename])

    reader = tf.TFRecordReader()
    _, serialized_example = reader.read(filename_queue)   #返回文件名和文件
    features = tf.parse_single_example(serialized_example,
                                       features={
                                           'label': tf.FixedLenFeature([], tf.int64),
                                           'img_raw' : tf.FixedLenFeature([], tf.string),
                                       })
    try:
        img = tf.decode_raw(features['img_raw'], tf.uint8)
        img = tf.reshape(img, [ 64, 64, 3])
        #img = tf.cast(img, tf.float32) * (1. / 255) - 0.5
        label = tf.cast(features['label'], tf.int32)

        return img, label
    except:
        print('This is a 8 bit picture')

In [3]:
path = 'D:\\code\\tianchi\\zhijiang\\0920\\dataset\\DatasetA_train_20180813\\DatasetA_train_20180813\\'
img, label = read_and_decode(path + 'datasetA_train_RGB')

In [4]:
img,label

(<tf.Tensor 'Reshape:0' shape=(64, 64, 3) dtype=uint8>,
 <tf.Tensor 'Cast:0' shape=() dtype=int32>)

In [5]:
img_batch, label_batch = tf.train.shuffle_batch([img, label],
                                                batch_size=10, capacity=5000,
                                                min_after_dequeue=2000)

In [8]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(coord = coord)
    
    for _ in range(100):
        val,a = sess.run([img_batch,label_batch])
        #print(val)
        print(a)
    #print(sess.run(label))

[101 102 107 100 104 100 104 106 107 103]
[103   1 107 105 103 105 105   1 107 103]
[102 100 104 104  10 100 107 100 104 108]
[105 102 102 104 107   1 107 104 104 104]
[102 103 103 100 103  10 100 108 102 103]
[ 10 101 104  10 107 107 104 105  10 103]
[103 103 103 102   1 102 107 106 104 108]
[107 100 105 101 102 104 100 107 104 103]
[ 10 104 102 106 103  10 106 106 107 107]
[ 10 105  10 101 106 105 107 104 101 102]
[101  10 105 102 106 103   1 102 107 106]
[104 106 104 100   1   1 105 103 101 106]
[106 103 104 105   1 104 105  10 105 101]
[103 108   1 104 102 107 105 107  10 107]
[  1 108 108 100 107 109 104 101 107 101]
[100 107  10 103 100 103 103 104 108 101]
[  1 100 100 104 102 106   1  10 105 105]
[106 101 104 104 105 100 102 103 104 106]
[106 102  10 107 108 100 103 104 106 106]
[103 100 109 104 103 103 106   1 101 108]
[105 100 108 102 100 100   1   1 101 108]
[ 10 106 103 108 102 104 105 109  10 104]
[105 103 102 108 106 100 109   1 103 101]
[105 101  10 104  10 102 108  10  